# Generated by Django 5.2.3 on 2025-07-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_customer_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reservation_day',
            field=models.CharField(default='Monday', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='seats',
            field=models.IntegerField(default=2),
        ),
    ]
