# Generated by Django 5.2.3 on 2025-07-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='count',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='booking_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
    ]
